apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-04-23T16:02:51Z"
  generation: 1
  labels:
    app: node-exporter
  name: node-exporter
  namespace: default
  resourceVersion: "7964"
  uid: cb0365fd-fde4-42eb-bc12-281628331911
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        imagePullPolicy: Always
        name: node-exporter
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-04-23T16:02:54Z"
    lastUpdateTime: "2022-04-23T16:02:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-04-23T16:02:51Z"
    lastUpdateTime: "2022-04-23T16:02:54Z"
    message: ReplicaSet "node-exporter-79786b8c55" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
